[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.79"
heck = "0.4.1"
indexmap = "2.2.0"
oxc = "0.5.0"
prettyplease = "0.2.16"
proc-macro2 = "1.0.78"
quote = "1.0.35"
serde = "1.0.196"
syn = "2.0.48"
