[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
heck.workspace = true
indexmap.workspace = true
oxc.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
